"""Start the two services: the per-problem Neo4j database and the MCP service.

Safe to repeat:  python -m agentdiscover.orchestrator.services ensure --problem X
Neo4j data persists in runs/<problem>/neo4j-data/; backend "none" needs an external
database at NEO4J_URI. The MCP service is a host process and holds the database password.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from .. import config, db, runconfig, sandbox

# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def _images_cache() -> Path:
    return config.repo_root() / "runs" / ".images"


def _pidfile_start(pidfile: Path, pid: int) -> None:
    pidfile.write_text(str(pid))


def _pidfile_alive(pidfile: Path) -> int | None:
    if not pidfile.exists():
        return None
    try:
        pid = int(pidfile.read_text().strip())
    except ValueError:
        return None
    return pid if sandbox.pid_alive(pid) else None


def _bolt_answers() -> bool:
    """Cheap TCP probe of the bolt port — is *something* listening?"""
    import socket

    host_port = config.neo4j_uri().split("://", 1)[1]
    host, port = host_port.rsplit(":", 1)
    try:
        with socket.create_connection((host, int(port)), timeout=2):
            return True
    except OSError:
        return False


# ---------------------------------------------------------------------------
# Neo4j
# ---------------------------------------------------------------------------

# The HTTP connector is disabled: it fails inside a converted SIF and only bolt is needed.
_NEO4J_CONF = """\
# Generated by agentdiscover (services.py) — edit NEO4J_* env vars, not this file.
server.directories.data=/data
server.directories.logs=/logs
server.directories.run=/logs/run
server.default_listen_address=127.0.0.1
server.bolt.listen_address=127.0.0.1:{bolt}
server.http.enabled=false
server.memory.heap.initial_size=512m
server.memory.heap.max_size=1g
server.memory.pagecache.size=512m
dbms.usage_report.enabled=false
# Cap the processor count: Neo4j sizes its event loops from it, and on a many-core node
# they can exhaust the file-descriptor limit.
server.jvm.additional=-XX:ActiveProcessorCount=4
"""


def ensure_neo4j(problem: str, backend: str) -> str:
    """Start the database if it is not running. Returns a one-line status."""
    if backend == "none":
        if not _bolt_answers():
            raise SystemExit(
                "SANDBOX_BACKEND=none: no container is started for Neo4j, so an external "
                f"database must already be listening at {config.neo4j_uri()} — none is."
            )
        return "neo4j: external instance (backend none)"

    rd = config.runs_dir(problem)
    data_dir = rd / "neo4j-data"
    logs_dir = rd / "neo4j-logs"
    # Fresh means no auth store yet, not merely no directory, so a first run that died
    # before setting the password retries that step.
    fresh = not (data_dir / "dbms").exists()
    for d in (data_dir, logs_dir, logs_dir / "run"):
        d.mkdir(parents=True, exist_ok=True)

    name = f"agentdiscover-neo4j-{problem}"
    user, password = config.neo4j_auth()

    if backend in ("docker", "podman"):
        running = subprocess.run(
            [backend, "ps", "-q", "--filter", f"name=^{name}$"],
            capture_output=True, text=True,
        )
        if running.stdout.strip():
            return f"neo4j: already running ({backend} container {name})"
        spec = sandbox.SandboxSpec(
            backend=backend,
            image=config.NEO4J_IMAGE,
            command=[],
            mounts=[
                sandbox.Mount(data_dir, "/data", ro=False),
                sandbox.Mount(logs_dir, "/logs", ro=False),
            ],
            env={
                "NEO4J_AUTH": f"{user}/{password}",
                "NEO4J_server_default__listen__address": "127.0.0.1",
                "NEO4J_server_bolt_listen__address": f"127.0.0.1:{config.NEO4J_BOLT_PORT}",
                "NEO4J_server_http_listen__address": f"127.0.0.1:{config.NEO4J_HTTP_PORT}",
                "NEO4J_dbms_usage__report_enabled": "false",
            },
            network="host",
            name=name,
            extra_args=["-d"],
        )
        subprocess.run(sandbox.build_argv(spec), check=True, capture_output=True, text=True)
        return f"neo4j: started ({backend} container {name}, {'fresh' if fresh else 'existing'} data)"

    # apptainer / singularity / enroot: the image entrypoint needs a writable image, so
    # run `neo4j console` with a generated neo4j.conf and manage it by pidfile.
    pidfile = rd / "neo4j.pid"
    if _pidfile_alive(pidfile):
        return "neo4j: already running (pid " + pidfile.read_text().strip() + ")"
    if _bolt_answers():
        return "neo4j: already running (bolt port answers)"

    conf_dir = rd / "neo4j-conf"
    conf_dir.mkdir(parents=True, exist_ok=True)
    (conf_dir / "neo4j.conf").write_text(_NEO4J_CONF.format(bolt=config.NEO4J_BOLT_PORT))
    image = sandbox.prepare_image(backend, config.NEO4J_IMAGE, _images_cache())
    mounts = [
        sandbox.Mount(data_dir, "/data", ro=False),
        sandbox.Mount(logs_dir, "/logs", ro=False),
        sandbox.Mount(conf_dir, "/conf", ro=True),
    ]
    env = {"NEO4J_CONF": "/conf"}

    if fresh:
        setpw = sandbox.SandboxSpec(
            backend=backend, image=image,
            command=["neo4j-admin", "dbms", "set-initial-password", password],
            mounts=mounts, env=env,
        )
        result = sandbox.run(setpw, wall_seconds=120)
        if result.returncode != 0:
            raise SystemExit(f"neo4j-admin set-initial-password failed:\n{result.stderr[-2000:]}")

    spec = sandbox.SandboxSpec(
        backend=backend, image=image,
        command=["neo4j", "console"],
        mounts=mounts, env=env,
    )
    pid = sandbox.spawn_detached(spec, rd / "neo4j-console.log")
    _pidfile_start(pidfile, pid)
    return f"neo4j: started ({backend} pid {pid}, {'fresh' if fresh else 'existing'} data)"


def stop_neo4j(problem: str, backend: str) -> None:
    name = f"agentdiscover-neo4j-{problem}"
    if backend in ("docker", "podman"):
        subprocess.run([backend, "stop", name], capture_output=True, check=False)
        return
    pidfile = config.runs_dir(problem) / "neo4j.pid"
    pid = _pidfile_alive(pidfile)
    if pid:
        sandbox.stop_detached(pid, grace=30)
    pidfile.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# The MCP service (host process)
# ---------------------------------------------------------------------------


def _health() -> dict | None:
    try:
        with urllib.request.urlopen(f"{config.service_url()}/health", timeout=2) as resp:
            return json.loads(resp.read().decode())
    except (urllib.error.URLError, OSError, ValueError):
        return None


def _code_fingerprint() -> str:
    """A hash of the service's own source, to detect a service started from older code."""
    h = hashlib.sha256()
    for path in sorted((config.repo_root() / "agentdiscover").rglob("*.py")):
        h.update(path.relative_to(config.repo_root()).as_posix().encode())
        h.update(path.read_bytes())
    return h.hexdigest()


def ensure_service(problem: str, backend: str) -> str:
    rd = config.runs_dir(problem)
    rd.mkdir(parents=True, exist_ok=True)
    fingerprint = _code_fingerprint()
    stamp = rd / "service.fingerprint"
    health = _health()
    if health is not None:
        if health.get("problem") != problem:
            raise SystemExit(
                f"An MCP service for problem {health.get('problem')!r} already holds port "
                f"{config.SERVICE_PORT}. One problem per host at a time — stop it first "
                f"(python -m agentdiscover.orchestrator.services stop --problem {health.get('problem')}) "
                f"or set AGENTDISCOVER_PORT/NEO4J_PORT to run this problem on other ports."
            )
        if stamp.exists() and stamp.read_text().strip() == fingerprint:
            return "service: already running"
        # Same problem, different code: restart. Safe: ensure runs before any agent.
        stop_service(problem)
        time.sleep(1.0)

    log = open(rd / "service.log", "ab")
    proc = subprocess.Popen(
        [sys.executable, "-m", "agentdiscover.server.app", "--problem", problem, "--backend", backend],
        stdout=log, stderr=log, start_new_session=True,
        env={**os.environ, "AGENTDISCOVER_ROOT": str(config.repo_root())},
    )
    (rd / "service.pid").write_text(str(proc.pid))

    deadline = time.monotonic() + 60
    while time.monotonic() < deadline:
        if _health() is not None:
            stamp.write_text(fingerprint)
            return f"service: started (pid {proc.pid}, http://127.0.0.1:{config.SERVICE_PORT})"
        if proc.poll() is not None:
            break
        time.sleep(0.5)
    raise SystemExit(
        f"MCP service did not become healthy — see {rd / 'service.log'}"
    )


def stop_service(problem: str) -> None:
    pidfile = config.runs_dir(problem) / "service.pid"
    pid = _pidfile_alive(pidfile)
    if pid:
        sandbox.stop_detached(pid)
    pidfile.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Starting over
# ---------------------------------------------------------------------------

# Run state that reset archives. Caches (eval-data/, eval-deps/, runs/.images/) are
# deliberately not listed and are left alone.
_RUN_STATE = ("neo4j-data", "neo4j-conf", "neo4j-logs", "meta-logs", "run.log",
              "service.log", "neo4j-console.log", "service.fingerprint",
              "meta-pass.json", "STOP", "neo4j.pid", "service.pid")


def reset(problem: str, backend: str) -> None:
    """Archive this problem's run state so the next run starts from iteration 1.
    The state is moved to runs/_archive/<problem>-<stamp>/, never deleted."""
    rd = config.runs_dir(problem)
    if not rd.exists():
        print(f"reset: nothing to archive for {problem} — starting fresh")
        return

    # Stop the services first: they hold neo4j-data/ open.
    stop_service(problem)
    stop_neo4j(problem, backend)

    targets = [rd / n for n in _RUN_STATE] + sorted(rd.glob("agent-*"))
    targets = [p for p in targets if p.exists()]
    if not targets:
        print(f"reset: nothing to archive for {problem} — starting fresh")
        return

    dest = config.repo_root() / "runs" / "_archive" / \
        f"{problem}-{time.strftime('%Y%m%d-%H%M%S')}"
    dest.mkdir(parents=True)
    for path in targets:
        path.rename(dest / path.name)
    print(f"reset: archived {len(targets)} item(s) to {dest.relative_to(config.repo_root())}")
    print("reset: caches kept (eval-data/, eval-deps/, runs/.images/)")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def ensure_all(problem: str, backend: str, only: str = "all") -> None:
    if only in ("all", "neo4j"):
        print(ensure_neo4j(problem, backend))
        db.wait_until_ready()
        n = db.apply_schema()
        print(f"neo4j: schema applied ({n} statements)")
        # Publish the run's settings before anything reads them. This is the only place
        # the environment is consulted; every process reads them from the database.
        values = runconfig.publish(problem)
        summary = runconfig.summary(values)
        # Report the timeout actually enforced; the launcher may raise the stored value.
        effective = runconfig.required_agent_timeout(problem)
        configured = int(values["agent_timeout"])
        if effective != configured:
            summary = summary.replace(
                f"agent_timeout={configured}",
                f"agent_timeout={effective} (raised from {configured})")
        print(f"config: {summary}")
    if only in ("all", "service"):
        print(ensure_service(problem, backend))
    if only == "all":
        # Build the evaluation environment now, so a failure stops the run here. Gated on
        # "all" because it needs the RunConfig published above to resolve the image.
        from ..server import evaluator
        print(evaluator.prepare(problem, backend))


def main() -> None:
    parser = argparse.ArgumentParser(prog="agentdiscover.orchestrator.services")
    sub = parser.add_subparsers(dest="cmd", required=True)
    for cmd in ("ensure", "stop", "status", "reset"):
        p = sub.add_parser(cmd)
        p.add_argument("--problem", required=True)
        p.add_argument("--backend", default=None)
        if cmd == "ensure":
            p.add_argument("--only", choices=("all", "neo4j", "service"), default="all")
    args = parser.parse_args()
    backend = args.backend or sandbox.detect_backend()

    if args.cmd == "ensure":
        ensure_all(args.problem, backend, args.only)
    elif args.cmd == "reset":
        reset(args.problem, backend)
    elif args.cmd == "stop":
        stop_service(args.problem)
        stop_neo4j(args.problem, backend)
        print("stopped.")
    elif args.cmd == "status":
        print("backend:", backend)
        print("bolt answering:", _bolt_answers())
        print("service health:", _health())


if __name__ == "__main__":
    main()
